### PR TITLE
Pull Request Fraction w/out Test

### PR DESCRIPTION
**Pull request by estebangorostiaga**
**Testing**:
- Need to decide if testing will be done in the same way Team 9 has, or if we continue Pytest

**How Pull Request Fraction works** 
-  It scans the current files in the Repository with the help of cloc
- It will track all of the changes of the files that have maintained their current path, and track very little changes from files that have changed directory or filenames 
- (e.g src/server.py) if server.py was named server1.py previously for example, and then changed to just server.py, with no code additions or deletions, the line counts for the file will be 0 because server1.py doesn't exist anymore by how cloc scans files, and scan.py could've been committed instead of being merged by a pull request
- This does hinder the total fraction of very big repositories (react, react-native), that received a fraction of 2% when tested
- Other repositories like express, and others we've used have passed with flying colors with fractions above 60%
- Our Project 1 Repository for example received a 51%, due to the fact of last minute direct commits to the Repo, and the fact that we changed our directories and paths a lot

**Solution**
- Open to any solutions to solve this problem if anything

### CODE REVIEW

**Comment by realkevinkwon** [comment]
I'm a little confused. Is this pull request asking about changing the way we test the metrics or how one of the metrics is calculated?

**Comment by estebangorostiaga** [comment]
> I'm a little confused. Is this pull request asking about changing the way we test the metrics or how one of the metrics is calculated?

- It’s commenting about the current way the metric is calculated, and raising a question if we should change the way we test, and if the metric should change if anything at all.

**Comment by realkevinkwon** [comment]
The PR fraction metric seems to be pretty complex to implement. We would need some way of determining what lines of code were introduced via pull requests with code reviews.

Correct me if I'm wrong, but does your code only look at merged files? Is there some way maybe git blame could be used for this metric?

**Comment by estebangorostiaga** [comment]
I added a filter to the GraphQL call using "reviews(first:1)". This will now filter all Pull Requests that have at least one review on them, and omit all others that haven't!

**Review by realkevinkwon — COMMENTED** [review]
looks good to me!

**Pull request merged**
