### PR TITLE
restler implemented

### PR DESCRIPTION
**Pull request by Chise7**
restler is complete, just needs to be ran again and documented after more implementation is done

Current Reports:
0/11 Test Cases passed (likely due to there being nothing to test)

### CODE REVIEW

**Comment by Chise7** [comment]
This may not need to actually be added to the code base, its more of a tool to be added rather than a code addition

**Comment by realkevinkwon** [comment]
Can you clarify what's being implemented here?

**Comment by PC192** [comment]
REST API Fuzzing
He's just covering the security requirements with an automated test.
I think Esteban just needs to PR in his backend items first and this will be more apparent in use.

**Review by realkevinkwon — APPROVED** [review]
LGTM

**Pull request closed without merging**
